import 'package:untitled1/hive_models/ingredient_model.dart';

List<NutrientModel> nutrientList = [
  NutrientModel(nutrientName: "Crude protein (g/100g)", amount: 0.0),
  NutrientModel(nutrientName: "Crude fat (g/100g)", amount: 0.0),
  NutrientModel(nutrientName: "Crude ash (g/100g)", amount: 0.0),
  NutrientModel(nutrientName: "Moisture (g/100g)", amount: 0.0),
  NutrientModel(nutrientName: "Crude fiber (g/100g)", amount: 0.0),
  NutrientModel(nutrientName: "Calcium (mg/100g)", amount: 0.0),
  NutrientModel(nutrientName: "Iron (mg/100g)", amount: 0.0),
  NutrientModel(nutrientName: "Magnesium (mg/100g)", amount: 0.0),
  NutrientModel(nutrientName: "Phosphorus (mg/100g)", amount: 0.0),
  NutrientModel(nutrientName: "Potassium (mg/100g)", amount: 0.0),
  NutrientModel(nutrientName: "Sodium (mg/100g)", amount: 0.0),
  NutrientModel(nutrientName: "Zinc (mg/100g)", amount: 0.0),
  NutrientModel(nutrientName: "Copper (mg/100g)", amount: 0.0),
  NutrientModel(nutrientName: "Manganese (mg/100g)", amount: 0.0),
  NutrientModel(nutrientName: "Selenium (µg/100g)", amount: 0.0),
  NutrientModel(nutrientName: "Vitamin A (IU/100g)", amount: 0.0),
  NutrientModel(nutrientName: "Vitamin E (mg/100g)", amount: 0.0),
  NutrientModel(nutrientName: "Vitamin D (IU/100g)", amount: 0.0),
  NutrientModel(nutrientName: "Vitamin C (mg/100g)", amount: 0.0),
  NutrientModel(nutrientName: "Thiamin (mg/100g)", amount: 0.0),
  NutrientModel(nutrientName: "Riboflavin (mg/100g)", amount: 0.0),
  NutrientModel(nutrientName: "Niacin (mg/100g)", amount: 0.0),
  NutrientModel(nutrientName: "Pantothenic (mg/100g)", amount: 0.0),
  NutrientModel(nutrientName: "Vitamin B6(mg/100g)", amount: 0.0),
  NutrientModel(nutrientName: "Vitamin B12 (µg/100g)", amount: 0.0),
  NutrientModel(nutrientName: "Choline (mg/100g)", amount: 0.0),
  NutrientModel(nutrientName: "Vitamin K1 (µg/100g)", amount: 0.0),
  NutrientModel(nutrientName: "Folic acid (µg/100g)", amount: 0.0),
  NutrientModel(nutrientName: "Tryptophan (g/100g)", amount: 0.0),
  NutrientModel(nutrientName: "Threonine (g/100g)", amount: 0.0),
  NutrientModel(nutrientName: "Isoleucine (g/100g)", amount: 0.0),
  NutrientModel(nutrientName: "Leucine (g/100g)", amount: 0.0),
  NutrientModel(nutrientName: "Lysine (g/100g)", amount: 0.0),
  NutrientModel(nutrientName: "Methionine (g/100g)", amount: 0.0),
  NutrientModel(nutrientName: "Cystine (g/100g)", amount: 0.0),
  NutrientModel(nutrientName: "Phenylalanine (g/100g)", amount: 0.0),
  NutrientModel(nutrientName: "Tyrosine (g/100g)", amount: 0.0),
  NutrientModel(nutrientName: "Valine (g/100g)", amount: 0.0),
  NutrientModel(nutrientName: "Arginine (g/100g)", amount: 0.0),
  NutrientModel(nutrientName: "Histidine (g/100g)", amount: 0.0),
  NutrientModel(nutrientName: "Alanine (g/100g)", amount: 0.0),
  NutrientModel(nutrientName: "Aspartic acid (g/100g)", amount: 0.0),
  NutrientModel(nutrientName: "Glutamic acid (g/100g)", amount: 0.0),
  NutrientModel(nutrientName: "Glycine (g/100g)", amount: 0.0),
  NutrientModel(nutrientName: "Proline (g/100g)", amount: 0.0),
  NutrientModel(nutrientName: "Serine (g/100g)", amount: 0.0),
  NutrientModel(nutrientName: "Linoleic acid (g/100g)", amount: 0.0),
  NutrientModel(nutrientName: "Alpha linolenic acid (g/100g)", amount: 0.0),
  NutrientModel(nutrientName: "Arachidonic Acid (g/100g)", amount: 0.0),
  NutrientModel(nutrientName: "DHA (g/100g)", amount: 0.0),
  NutrientModel(nutrientName: "EPA (g/100g)", amount: 0.0),
  NutrientModel(nutrientName: "Chloride (mg/100g)", amount: 0.0),
  NutrientModel(nutrientName: "Iodine (mg/100g)", amount: 0.0),
  NutrientModel(nutrientName: "Taurine (g/100g)", amount: 0.0),
  NutrientModel(nutrientName: "Biotin (mg/100g)", amount: 0.0),
  NutrientModel(nutrientName: "L-carnitrine (g/100g)", amount: 0.0),
  NutrientModel(nutrientName: "Price (THB/100g)", amount: 0.0),
];
